version: '3'

services:
  'nextjs-ui':
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: 'nextjs-ui'
    ports:
      - "3000:3000"
    # If you want local changes to update the Docker container, you can pass through project files like this:
    volumes:
      - ./:/srv/www
    # volumes:
    #   - ./layout:/srv/www/layout
    #   - ./pages:/srv/www/pages
    #   - ./server:/srv/www/server
    #   - ./static:/srv/www/static

    # OPTIONAL: If you want to override the command in the Dockerfile, specify it here
    # command: bash -c "cd /srv/www && npm install && npm run dev"

    # env_file:
    #   - ./path/to/.env

    # environment:
    #   EXAMPLE_VAR: 'true'
    #   EXAMPLE_VAR2: 'secret'

    # depends_on:
    #   - mongodb
    #   - rabbitmq

  # mongodb:
  #   image: mongo:latest
  #   container_name: "nextjs-mongodb"
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - ./docker/mongodb/data/db:/data/db
  #   ports:
  #     - "27017:27017"
  #   command: mongod --smallfiles --logpath=/dev/null # --quiet

  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #     - "5672:5672"
  #   expose:
  #     - "5672"
